spring:
  h2:
    console:
      enabled: 'true'
      path: /console
      settings:
        web-allow-others: 'true'
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:h2:file:./resources/database
    username: 'sa'
    password: ''
  main:
    allow-bean-definition-overriding: 'true'