chain: matic
maxRps: 1
minSwapQuote: 20
randomSwapQuote: true
minAdvantage: 2.5
gasPriceLimit: 1000
minimalCoinBalance: 10
refillCoinQuote: 50
maximalTokenShare: 0.6
complexityLevel: 3
excludedTokens:
  - UST
excludedProtocols:
  - POLYGON_ONE_INCH_LIMIT_ORDER

increasedGasLimit: 1.25
defaultSlippage: 1.0
allowPartialFill: true
timeout: 5
