chain: matic
maxRps: 5
minSwapQuote: 200
randomSwapQuote: true
minAdvantage: 5.0
gasPriceLimit: 1000
gasLimit: 4000000
minimalCoinBalance: 10
refillCoinQuote: 50
maximalTokenShare: 0.6
complexityLevel: 3
excludedTokens:
  -
excludedProtocols:
  - POLYGON_ONE_INCH_LIMIT_ORDER

defaultSlippage: 1.0
allowPartialFill: true
timeout: 5
