account: realAccount
chain: matic
maxRps: 1
minSwapQuote: 1.0
minAdvantage: 30.0
gasPriceMode: fast
gasPriceLimit: 1000

increasedGasLimit: 1.25
defaultSlippage:  1.0
allowPartialFill: true
timeout: 5
