account: fakeAccount
chain: matic
maxRps: 25
minSwapQuote: 1.0
minAdvantage: 0.3
gasPriceMode: fast
gasPriceLimit: 1000

increasedGasLimit: 1.25
defaultSlippage:  1.0
allowPartialFill: true
timeout: 5
