account: realAccount
chain: matic
myAddress: 0x0fad488c45e44B72A17e4eBFc20ce16ff284de3E
logDecimalPrecision: 3
minimalSwapQuote: 0.01
amountToSell: 0.05
demandPercentAdvantage: 0.5
maxSlippage: 1
increasedGasLimit: 1.25
increasedGasPrice: 3