account: realAccount
chain: matic
myAddress: ***REMOVED***
timeout: 5
maxRps: 1
waitTimeAfterSwap: 60
minimalSwapQuote: 1.0
allowPartialFill: true
swapSettings:
  - advantage: 30.0
    slippage:  0.1
increasedGasLimit: 1.25
increasedGasPrice: 2
logDecimalPrecision: 2