account: realAccount
chain: matic
myAddress: ***REMOVED***
timeout: 5
logDecimalPrecision: 2
minimalSwapQuote: 1.0
advantage:
  - 0.1
  - 0.2
  - 0.3
increasedGasLimit: 1.25
increasedGasPrice: 2
sleepTime: 1