account: realAccount
chain: matic
myAddress: ***REMOVED***
timeout: 5
sleepTime: 200
waitTimeAfterSwap: 60
minimalSwapQuote: 1.0
allowPartialFill: true
swapSettings:
  - advantage: 0.2
    slippage:  0.3
  - advantage: 0.5
    slippage:  0.7
  - advantage: 1.0
    slippage:  1.3
increasedGasLimit: 1.25
increasedGasPrice: 2
logDecimalPrecision: 2