account: fakeAccount
chain: matic
maxRps: 25
minSwapQuote: 1.0
minAdvantage: 0.3
gasPriceLimit: 1000
maxTimeNoTransaction: 8
minimalCoinBalance: 10
refillCoinQuote: 50
maximalTokenShare: 0.6
excludedTokens:
  - NONE

increasedGasLimit: 1.25
defaultSlippage:  1.0
allowPartialFill: true
timeout: 5
