account: fakeAccount
chain: matic
myAddress: ***REMOVED***
timeout: 5
maxRps: 1
waitTimeAfterSwap: 60
minimalSwapQuote: 1.0
allowPartialFill: true
advantage: 30.0
slippage:  1.0
increasedGasLimit: 1.25
increasedGasPrice: 2