account: fakeAccount
chain: matic
maxRps: 1
loweredRps: 5
loweredRpsTimeMinutes: 20
minSwapQuote: 20
randomSwapQuote: true
minAdvantage: 2.5
gasPriceLimit: 1000
maxTimeNoTransaction: 8
minimalCoinBalance: 10
refillCoinQuote: 50
maximalTokenShare: 0.6
excludedTokens:
  - UST
excludedProtocols:
  - POLYGON_ONE_INCH_LIMIT_ORDER

increasedGasLimit: 1.25
defaultSlippage: 1.0
allowPartialFill: true
timeout: 5
