proxyAddress: ***REMOVED***
ownerAddress: ***REMOVED***
chain: matic
maxRps: 5
minSwapQuote: 5
randomSwapQuote: true
minAdvantage: 2.5
gasPriceLimit: 1000
minimalCoinBalance: 10
refillCoinQuote: 50
maximalTokenShare: 0.6
complexityLevel: 3
excludedTokens:
  -
excludedProtocols:
  - POLYGON_ONE_INCH_LIMIT_ORDER

increasedGasLimit: 1.25
defaultSlippage: 1.0
allowPartialFill: true
timeout: 5
